### ISSUE TITLE
[ERD] ERD 파트 ERD 작성

### ISSUE THREAD

**Issue by pinomaker-hoo** [HooAndFriend/dice-backend#17]

**Comment by rlawnaks** [comment]
![image](https://github.com/HooAndFriend/dice-backend/assets/105625545/927a662b-b883-41ae-9f56-37f456dfd04e)

**Comment by pinomaker-hoo** [comment]
@rlawnaks 

TB_TABLE에는 TABLE에 대한 comment 추가하면 좋을 거 같아요

TB_ROW에는 Unique, AUTO_INCREMENT, CURRENT_STAMP와 같은 옵션도 넣을 수 있어야할 거 같고, FK 여부 표시도 필요해보입니다.

타 Table과 매핑 관계 여부 파악은 어떻게 하나요??

**Comment by rlawnaks** [comment]
![image](https://github.com/HooAndFriend/dice-backend/assets/105625545/32594ffb-690c-44b5-bd32-4696e0d09e77)

**Comment by rlawnaks** [comment]
key 컬럼에서 해당 컬럼이 PK 인지 FK인지 일반 컬럼인지 여부를 판단하려고 합니다

**Comment by pinomaker-hoo** [comment]
@rlawnaks 
TB_MAPPING은 어떤 용도인가요?

**Comment by rlawnaks** [comment]
테이블간 연관 관계를 나타내기 위한 용도입니다

**Comment by rlawnaks** [comment]
그리고 연관된 FK도 관리하기 위한 용도입니다
