### ISSUE TITLE
Api, Collection ERD 작성

### ISSUE THREAD

**Issue by yoonali** [HooAndFriend/dice-backend#5]
![image](https://github.com/HooAndFriend/dice-backend/assets/103414935/d1ed5957-ffd7-4dbb-a00b-73e2894d310a)
![image](https://github.com/HooAndFriend/dice-backend/assets/103414935/ccb5f156-556c-4f09-8e14-2f28d7c482b5)

**Comment by pinomaker-hoo** [comment]
TB_COLLECTION 테이블 리뷰
1. col_name은 default Value가 있는 데 Null 허용인가요?

TB_API 테이블 리뷰
1. api_name은 default value가 있는 데, 왜 null 허용인가요?
2. method는 ENUM 처리해서 관리하는 것이 좋을 거 같아요.
3. 단순하게 method와 url 뿐만 아니라 넘어가는 body, header에 대한 값도 저장해야합니다.

**Comment by yoonali** [comment]
![image](https://github.com/HooAndFriend/dice-backend/assets/103414935/f4910325-c956-4923-8103-5c993542b272)
수정했습니다! body, header 타입이 이게 맞나요?
